<div class="widget block block-static-block">
<?php if($block->getData('widgettitle')): ?>
	<div class="block-title"><strong><?= $block->getData('widgettitle') ?></strong></div>
<?php endif; ?>
	<div class="row">
		<div class="owl-carousel">
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/sarten.png"); ?>" />
				<ul class="detalle-producto">
					<li><strong>Sartén Eléctrico Oster</strong></li>
					<li>Oster / CKSTSKSH12</li>
					<li>Código: 1005</li>
					<li style="color: #f47920;font-weight: 800;">₡20,200 </li>
				</ul>
			</div>
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/enfriador.png"); ?>" />
                                <ul class="detalle-producto">
                                	<li><strong>Sartén Eléctrico Oster</strong></li>
                                        <li>Oster / CKSTSKSH12</li>
                                        <li>Código: 1005</li>
                                        <li style="color: #f47920;font-weight: 800;">₡20,200 </li>
				                </ul>
			</div>
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/enfriador.png"); ?>" />
                                <ul class="detalle-producto">
                        		<li><strong>Sartén Eléctrico Oster</strong></li>
                                        <li>Oster / CKSTSKSH12</li>
                                        <li>Código: 1005</li>
                                        <li style="color: #f47920;font-weight: 800;">₡20,200 </li>
			        </ul>
			</div>
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/cafetera.png"); ?>" />
                                <ul class="detalle-producto">
                                	<li><strong>Sartén Eléctrico Oster</strong></li>
                                        <li>Oster / CKSTSKSH12</li>
                                        <li>Código: 1005</li>
                                        <li style="color: #f47920;font-weight: 800;">₡20,200 </li>
				</ul>
			</div>
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/cocina.png"); ?>" />
                                <ul class="detalle-producto">
                                	<li><strong>Sartén Eléctrico Oster</strong></li>
                                        <li>Oster / CKSTSKSH12</li>
                                        <li>Código: 1005</li>
                                        <li style="color: #f47920;font-weight: 800;">₡20,200 </li>
				</ul>
			</div>
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/horno.png"); ?>" />
                                <ul class="detalle-producto">
                                	<li><strong>Sartén Eléctrico Oster</strong></li>
                                        <li>Oster / CKSTSKSH12</li>
                                        <li>Código: 1005</li>
                                        <li style="color: #f47920;font-weight: 800;">₡20,200 </li>
				</ul>
			</div>
  			<div class="espacio">
				<img src="<?= $block->getViewFileUrl("Coopelesca_Ofertas::images/enfriador.png"); ?>" />
                                <ul class="detalle-producto">
                                	<li><strong>Sartén Eléctrico Oster</strong></li>
                                        <li>Oster / CKSTSKSH12</li>
                                        <li>Código: 1005</li>
                                        <li style="color: #f47920;font-weight: 800;">₡20,200 </li>
				</ul>
			</div>	
		</div>
	</div>	
</div>
<script src="<?= $block->getViewFileUrl('Coopelesca_Ofertas::js/acciones-ofertas.js'); ?>" ></script>
