<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $om = \Magento\Framework\App\ObjectManager::getInstance();  
    $resolver = $om->get('Magento\Framework\Locale\Resolver');
    $langCode = $resolver->getLocale();
    $pos = strpos($langCode, "es");
?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
        <?php endif ?>
        <div class="row">
            <div id="productosOfertas" class="owl-carousel">
                    <?php foreach ($items as $_item): ?>                       
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details products-front-list">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                
                                <p class="descripcionProducto"><?= $_item->getShortDescription() ?> </p>
                                <p class="skuProducto"><strong><?= ((!($pos === false))) ? "C&oacute;digo" : "Sku" ?>:</strong>&nbsp;<?= $_item->getSku() ?> </p>
                                <p class="precioProducto"><?= $block->getProductPriceHtml($_item, $type) ?> </p>
                            </div>
                        </div>
                    <?php endforeach ?>
        </div>
    </div>
<?php endif;?>
</div>