<?php
if ($exist = ($this->getBestsellerProduct() && $this->getBestsellerProduct()->getPageSize())) {
  $wet_prodcollection = $this->getBestsellerProduct();
  $productcount = 10;
  $imagewidth = $this->getProductimagewidth();
  $imageheight = $this->getProductimageheight();
  $mode = 'grid';
  //OBTENER EL IDIOMA PARA TITULO 
  $om = \Magento\Framework\App\ObjectManager::getInstance();
  $resolver = $om->get('Magento\Framework\Locale\Resolver');
  $langCode = $resolver->getLocale();
  $pos = strpos($langCode, "es");
  if(!($pos === false)){
   $title = __('Lo más vendido');
  }else{
   $title = __('Bestseller Products');	
  }
  // END IDIOMA
  $type = 'widget-bestseller-grid';
  $image = 'bestseller_products_content_widget_grid';
}
?>



<?php if ($exist):?>
  <div class="block widget block-bestseller-products <?php echo $mode; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php  echo $title; ?></strong>
        </div>
        <div class="row">
            <div id="bestsellerProducts" class="owl-carousel">
        <?php
	foreach ($wet_prodcollection as $item):     
	  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
          $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());
	?>
    
    
        <div class="product-item-info">
        <?php 
            $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')
                                ->setImageFile($_product->getFile())
                                ->resize("240","300")
                                ->getUrl();
        ?>
            <a href="<?php  echo $_product->getProductUrl() ?>" class="product-item-photo">
               <img src="<?php echo $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
            </a>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                       href="<?php echo $_product->getProductUrl() ?>"
                       class="product-item-link">
                        <?php echo $block->escapeHtml($_product->getName()); ?>
                    </a>
                </strong>
                <?php //echo $_product->getShortDescription($item->getProductId()); ?>
                <p><strong>Sku:</strong>&nbsp;<?= $_product->getSku()?> </p>
                <?php //echo $this->getProductPriceHtml($_product, $type); ?>
            </div>    
        </div>
     		
        <?php endforeach; ?>
      </div>
     </div>
  </div>
<?php endif;?>
