<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$itemsCollection = $cart->getQuote()->getItemsCollection();
$itemsVisible = $cart->getQuote()->getAllItems();

$resolver = $objectManager->get('Magento\Framework\Locale\Resolver');
$langCode = $resolver->getLocale();
$pos = strpos($langCode, "es");

?>
<ul id="detalleCarritoCalculadora" class="list-group row pull-right-otros">
    <li class="list-group-item col-lg-2 encabezado hideSm"><?= ( $pos !== false ) ? "Producto" : "Product" ?></li>
    <li class="list-group-item col-lg-2 encabezado hideSm"><?= ( $pos !== false ) ? "Descripción" : "Description" ?></li>
    <li class="list-group-item col-lg-2 encabezado hideSm"><?= ( $pos !== false ) ? "Precio" : "Price" ?></li>
    <li class="list-group-item col-lg-2 encabezado hideSm"><?= ( $pos !== false ) ? "Cantidad" : "Quantity" ?></li>
    <li class="list-group-item col-lg-2 encabezado hideSm"><?= ( $pos !== false ) ? "Subtotal" : "Subtotal" ?></li>
<?php
foreach($itemsVisible as $item) {     
    $_product = $objectManager->get(\Magento\Catalog\Model\Product::class)->load($item->getData("product_id"));

    $store  = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
    $imageUrl   = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $_product->getImage();
    $mediaUrl   = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

    echo '<li class="list-group-item mt-5 col-lg-2 col-md-12 col-sm-12 col-xs-12"><p class="hideLg">'.(( $pos !== false ) ? "Producto" : "Product").'</p><img class="img-fluid" src="'.$imageUrl.'" /></li>';
    echo '<li class="list-group-item col-lg-2 col-md-12 col-sm-12 col-xs-12"><p class="hideLg">'.(( $pos !== false ) ? "Descripción" : "Description").'</p>'.strip_tags(substr($_product->getName(),0,100)).'</li>';    
    echo '<li class="list-group-item col-lg-2 col-md-3 col-sm-3 col-xs-3"><p class="hideLg">'.(( $pos !== false ) ? "Precio" : "Price").'</p><strong>₡'.number_format($item->getPrice(), 2, '.', ',').'</strong></li>';
    echo '<li class="list-group-item col-lg-2 col-md-3 col-sm-3 col-xs-3"><p class="hideLg">'.(( $pos !== false ) ? "Cantidad" : "Quantity").'</p>'.$item->getQty().'</li>';
    echo '<li class="list-group-item col-lg-2 col-md-3 col-sm-3 col-xs-3"><p class="hideLg">'.(( $pos !== false ) ? "Subtotal" : "Subtotal").'</p><strong>₡'.number_format(($item->getQty()*($item->getPrice())), 2, '.', ',').'</strong></li>';          
}
?>
</ul>