<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$buttonTitle = __('Add to Cart');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?php //echo $block->getAdditionalHtml(); ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products row wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
                $pedidoEspecial = false;
                $proCats = $_product->getCategoryIds();
                if( array_search(278, $proCats) !== false ){                    
                    $pedidoEspecial = true;
                }

                if($iterator++ == 1){
                    if($pedidoEspecial){
                        echo '<li class="item product especial col-lg-3 col-md-3 col-sm-5 col-xs-12">';
                    }else{
                        echo '<li class="item product col-lg-3 col-md-3 col-sm-5 col-xs-12">';
                    }
                }else{
                    if($pedidoEspecial){
                        echo '</li><li class="item product especial col-lg-3 col-md-3 col-sm-5 col-xs-12">'; 
                    }else{
                        echo '</li><li class="item product col-lg-3 col-md-3 col-sm-5 col-xs-12">'; 
                    }
                       
                }


             ?>       
                <div class="product-item-info" data-container="product-grid">                    
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <div class="wrap-detalle">
                            <?php 
                             if( trim($_product->getShortDescription()) != ""){ ?> 
                                <div class="short-description subtitulos"><?= /* @escapeNotVerified */ substr(trim($_product->getShortDescription()),0,20) ?></div>
                            <?php 
                             }
                             if( trim($_product->getSku()) != ""){ ?> 
                                <div class="sku subtitulos"><p><?= /* @escapeNotVerified */  trim($_product->getSku()) ?></p></div>
                            <?php 
                             } ?>
                        </div>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <div class="product-social-links">                            
                            <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php  echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">                                                                                
                                    </a>
                                <?php endif; ?>
                            </div>
                            <div data-role="add-to-links" class="actions-secondary">
                                <!-- AddToAny BEGIN -->
                                <div id="listaComparte" class="a2a_kit a2a_kit_size_32 a2a_default_style" data-a2a-url="<?= $_product->getProductUrl() ?>" data-a2a-title="<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">     
                                    <a class="a2a_button_facebook"></a>
                                    <a class="a2a_button_twitter"></a>                                
                                </div>
                                <script async src="https://static.addtoany.com/menu/page.js"></script>
                                <!-- AddToAny END -->
                            </div>
                        </div>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        
                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
                        $addToCartUrl =  $listBlock->getAddToCartUrl($_product); 

                        $om = \Magento\Framework\App\ObjectManager::getInstance();  
                        $resolver = $om->get('Magento\Framework\Locale\Resolver');
                        $langCode = $resolver->getLocale();
                        $posicion = strpos($langCode, "es");    ?>                    
                        <div class="boton-detalle-producto action primary tocart">
                            <?php if($posicion !== false){ ?>
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">M&aacute;s detalles</a>
                            <?php }else{ ?>
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">More details</a>
                            <?php } ?>                            
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
