<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="row">
    <div class="col-lg-5 col-md-5 col-xs-5">
        <div class="checkout-success">
            <?php if ($block->getOrderId()):?>
                <?php if ($block->getCanViewOrder()) :?>
                    <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
                <?php  else :?>
                    <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
                <?php endif;?>
                    <p>
                        <?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?>
                    </p>
            <?php endif;?>

            <?= $block->getAdditionalInfoHtml() ?>

            <div class="actions-toolbar">
                <div class="primary">
                    <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
                </div>
            </div>
        </div>
    </div> 
    <div class="col-lg-5 col-md-5 col-xs-5">   
        <div class="">
            <form id="mensajeFinalizaCompra">
                <input placeholder="" type="text" value="" />
            </form>
        </div>
    </div>    
</div>